In [1]:
! pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 10.0 MB/s  0:00:01 10.3 MB/s eta 0:00:01


In [2]:
import numpy as np
python_list=[1,2,3,4,5,6,7]
print(python_list)
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5]


In [4]:
# with default value
#np.zeros(shape)(3) fir 1d, (3,3) 2d
import numpy as np
zeroes_array=np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [6]:
#ones(shape)
import numpy as np
one=np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#full function

import numpy as np
filled=np.full((3,2),4)
print(filled)

[[4 4]
 [4 4]
 [4 4]]


In [10]:
#creating sequences of numbers in numpy
#arange()
#arange(start,stop,step)

import numpy as np
arr= np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [11]:
#creating identity matrices
#eye(size)
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# properties of numpy
# shape ,size,type
# no of dymention
import numpy as np
arr_2d= np.array([[1,2,3],
                [4,5,6]])
print(arr_2d.shape)

(2, 3)


In [4]:
#size
import numpy as np
#total number of element return korega
arr= np.array([[10,20,30],[40,50,60]])
print(arr.size)

6


In [7]:
#number of dymention
#ndim
import numpy as np
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)




1
2
3


In [8]:
#.dtype
# data type of elements
#(int)
import numpy as np
arr=np.array([10,20,30.5,40])
print(arr.dtype)

float64


In [9]:
#astype
# convert any datatype
#array.astype(newtype)
import numpy as np
arr=np.array([1.2,2.4,3.6])
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 2 3]
int64


In [12]:
#without using loops
#operator     example
#+             ar+2
#-             ar-2
#**             arr*3
#/             arr/2
#//            arr//2
#%             arr%3
import numpy as np
arr= np.array([10,20,30])
print(arr+5)
print(arr*5)
print(arr**5)

[15 25 35]
[ 50 100 150]
[  100000  3200000 24300000]


In [15]:
#aggregation function
# np.sum(array) add all
# np.mean(array) calculate average
# np.min(small)
# np.max(array)
# np.std(array) standard deviation
# np.var(arrat)    variance ber korar jonno
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


150
30.0
10
50
14.142135623730951
200.0


In [19]:
#indexing 
#slicing
#1,2,[3],4,5 single element pick
#or multiple  element pick start , stop step
#fancy indexing 
#boolean masking cirtain condition then fileter
#numpy 0 theke stat hota hei

#accessing
import numpy as np

"""
array[index] #1d array
array[row,collumn] #2d
"""
arr= np.array([10,20,30,40,50])
print(arr[0]) #first element
print(arr[2])
print(arr[-1])

10
30
50


In [23]:
#sliching
#extracting subset from an main array
"""
arr[start:end],start to end-1
"""
import numpy as np
arr=np.array([2,4,5,6,7,8,9,0,24,55,56])
print(arr[1:5:2])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[4 6]
[2 4 5 6]
[ 2  5  7  9 24 56]
[56 55 24  0  9  8  7  6  5  4  2]


In [26]:
#fancy indexing [selecting multiple element at once] 
#boolean masking  
import numpy as np
arr=np.array([2,4,5,6,7,8,9,0,24,55,56])
print(arr[[0,2,4]])

[2 5 7]


In [27]:
#filtering data
#10 time faster than loop
import numpy as np
arr=np.array([2,4,5,6,7,8,9,0,24,55,56])
print(arr[arr>25])

[55 56]


In [31]:
#reshaping and menupulating array
# dimention chage without chaging data
# arr.reshape()
# total number of element are in same 
"""
reshape(rows,columns) specify new shape
if dimention match
"""
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped_Arr=arr.reshape(2,3)
print(reshaped_Arr) # it can not create copy it  returns a view

[[1 2 3]
 [4 5 6]]


In [32]:
# flattening arrays
# revel() flatten()
# when u convert multidymention array to  one d array 
"""
.ravel()  ----> views
.flatten()  ---> copy

"""
import numpy as np
arr_2d= np.array([[1,2,3,],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [43]:
# add remove stack and split
# new datapoint -> add --> remove ----> marging -----> spliting
#np.innsert(index number)
#np.insert(array, index, vlue, asix=0 row wise 1 column wise)
import numpy as np
arr= np.array([10,20,30,40,50])
new_arr=np.insert(arr,2,100,axis=0)
#print(new_arr)
arr_2d= np.array([[1,2],[3,4]])
new_arr_2d=np.insert(arr_2d,1,[5,6],axis=1) # axis= 0,1,or None
print(new_arr_2d)

[[1 5 2]
 [3 6 4]]


In [44]:
#append
import numpy as np
arr= np.array([10,20,30,40,50])
new_arr=np.append(arr,[60,70,80])
print(new_arr)

[10 20 30 40 50 60 70 80]


In [45]:
#contatinent
"""
np.concatenate((array1,array2), axis=0)
axis 0--> vartical stacking
axis=1 ---> horizontal stacking

"""
import numpy as np
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
new_arr= np.concatenate((arr1,arr2),)
print(new_arr)

[1 2 3 4 5 6]


In [46]:
# remove elements of array or delete 
# delete()
"""
np.delete(array,index,axis=None)
flattern array

"""
import numpy as np
arr= np.array([10,20,30,40,50,60])
print(arr)
new_arr=np.delete(arr,0)
print(new_arr)
#multidimentional array

[10 20 30 40 50 60]
[20 30 40 50 60]


In [50]:
import numpy as np
arr_2d= np.array([[1,2,3],[4,5,6]])
new_arr_2d=np.delete(arr_2d,0,axis=0)
print(new_arr_2d)

[[4 5 6]]


In [52]:
#stacking and spliting
"""
vertically
horizontally
vstack() row wise
hstack() column wise

"""
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))



[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]


In [54]:
# spliting ---> multiple sub array me convert korna
"""
np.split()
np.hsplit()
np.vsplit()

"""
import numpy as np
arr= np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [59]:
# # Broodcasting
# [100,200,300] in taka  ---> flat 10% discount
prices= [100,200,300]
discount=10
final_prices=[]
for price in prices:
    final_price=price-(price*discount/100)
    final_prices.append(final_price)
print(final_prices)
# for time complexity problem in loop we are using broadcasting

[90.0, 180.0, 270.0]


In [60]:
import numpy as np
prices= np.array([100,200,300])
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [63]:
# how numpy handle arrays of different different shape
# matching dymention
# expanding single elements
#incompetible shapes
import numpy as np
arr= np.array([100,200,300])
result= arr*2
print(result)


[200 400 600]


In [64]:
#1d to 2d  array
import numpy as np
matrix= np.array([[1,2,3],[4,5,6]]) #2d
vector= np.array([10,20,30]) #1d
result= matrix+vector
print(result)

[[11 22 33]
 [14 25 36]]


In [65]:
# error
# if incompitable shape
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2])
result= arr1+ arr2
print(result)
# we can solve ths problem with reshape(row,column)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [69]:
#vectorization
list1=[1,2,3]
list2=[4,5,6]
result=[x+y for x,y in zip(list1,list2)] #list comprehention
print(result)

[5, 7, 9]


In [70]:
#vectorization
#faster than loops
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result= arr1+arr2
print(result)


[5 7 9]


In [72]:
#vectorization
#faster than loops
arr1=np.array([10,20,30])
multiplaied= arr*3
print(multiplaied)


[300 600 900]


In [ ]:
# Difference between Broadcasting and vectorization
# expand smaller arrays to larger array ---------> entire array 
# faster thna loop --------------------> 1000* faster
# 1d-> 2d -------------------> matrix operation me


In [74]:
# Handling Missing values
#why ---->
#buildin funtion
# np.isnan() ---> detect missing values
# np.nan_to_num()
#np.isinf() ----> detecting infinite values
#nan --> not a number  0/0  it returns boolean value
#np.isnun(array)
import numpy as np
arr=np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))
print(np.nan==np.nan) # nehi we can not compare them directly


[False False  True False  True False]
False


In [77]:
# nan_to_num
# np.nan_to_num(array,nan=value) defalt -0
import numpy as np
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr=np.nan_to_num(arr,nan=4)
print(cleaned_arr)

[1. 2. 4. 4. 4. 6.]


In [78]:
#handling infinite value
#np.isinf(array) 10^1000
#1/0
import numpy as np
arr=np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [79]:
#replace
import numpy as np
arr=np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))
cleaned_arr=np.nan_to_num(arr,posinf=1000,neginf=-1000)
print(cleaned_arr)

[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     6.]
